import os

from dotenv import load_dotenv

load_dotenv(override=True)


class Config:
    ENVIROMENT = os.getenv("ENVIROMENT")
    MONGODB_CONNECTION_URI = os.getenv("MONGODB_CONNECTION_URI")
    MONGODB_DATABASE_NAME = os.getenv("MONGODB_DATABASE_NAME")
    JWT_TOKEN_SECRET = os.getenv("JWT_TOKEN_SECRET")
    MONGODB_USER_DATABASE = os.getenv("MONGODB_USER_DATABASE")
    MONGODB_USER_DATABASE_COLLECTION = os.getenv("MONGODB_USER_DATABASE_COLLECTION")

    DB_NAME = os.getenv("DB_NAME")
    DB_USER = os.getenv("DB_USER")
    DB_PASS = os.getenv("DB_PASS")
    DB_HOST = os.getenv("DB_HOST")

    TIMESCALE_SERVICE_URL = os.getenv("TIMESCALE_SERVICE_URL")
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
    SecretKey = os.getenv("SecretKey")
    Encreaption_key = os.getenv("Encreaption_key")
    Secret_IV = os.getenv("Secret_IV")
    ALGORITHM = os.getenv("ALGORITHM")
    Access_key = os.getenv("Access_key")
    ORG_ID = os.getenv("ORG_ID")
    PROJECT_ID = os.getenv("PROJECT_ID")
    ALERTING_PROJECT_ID = os.getenv("ALERTING_PROJECT_ID")
    RTLAYER_AUTH = os.getenv("RTLAYER_AUTH")
    PORT = os.getenv("PORT", 8080)
    CHATBOTSECRETKEY = os.getenv("CHATBOTSECRETKEY")
    TEMPLATE_ID = os.getenv("TEMPLATE_ID")
    max_workers = os.getenv("max_workers")
    CHATBOT_OPTIONS_TEMPLATE_ID = os.getenv("CHATBOT_OPTIONS_TEMPLATE_ID")
    QUEUE_CONNECTIONURL = os.getenv("QUEUE_CONNECTIONURL")
    QUEUE_NAME = os.getenv("QUEUE_NAME")
    PREFETCH_COUNT = os.getenv("PREFETCH_COUNT")
    CONSUMER_STATUS = os.getenv("CONSUMER_STATUS")
    OPTIONS_APIKEY = os.getenv("OPTIONS_APIKEY")
    GCP_CREDENTIALS = os.getenv("GCP_CREDENTIALS")
    REDIS_URI = os.getenv("REDIS_URI")
    TIMESCALE_SERVICE_URL = os.getenv("TIMESCALE_SERVICE_URL")
    PUBLIC_REFERENCEID = os.getenv("PUBLIC_REFERENCEID")
    ADMIN_API_KEY = os.getenv("ADMIN_API_KEY")
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
    PINECONE_APIKEY = os.getenv("PINECONE_API_KEY")
    PINECONE_INDEX = os.getenv("PINECONE_INDEX")
    TRIGGER_PROJECT_ID = os.getenv("TRIGGER_PROJECT_ID", "")
    CHATBOT_ACCESS_KEY = os.getenv("Chatbot_Access_key")
    PUBLIC_CHATBOT_TOKEN = os.getenv("public_chatbot_token")
    LOG_QUEUE_NAME = os.getenv("LOG_QUEUE_NAME")
    ATATUS_LICENSE_KEY = os.getenv("ATATUS_LICENSE_KEY")
    DOCSTAR_ACCESS_KEY = os.getenv("DOCSTAR_ACCESS_KEY")
    DOCSTAR_ORG_ID = os.getenv("DOCSTAR_ORG_ID")
    DOCSTAR_COLLECTION_ID = os.getenv("DOCSTAR_COLLECTION_ID")
    AI_ML_APIKEY = os.getenv("AI_ML_APIKEY")
    AI_MIDDLEWARE_PAUTH_KEY = os.getenv("AI_MIDDLEWARE_PAUTH_KEY")
    OPENAI_API_KEY_GPT_5_NANO = os.getenv("OPENAI_API_KEY_GPT_5_NANO")
    HIPPOCAMPUS_API_KEY = os.getenv("HIPPOCAMPUS_API_KEY")
    HIPPOCAMPUS_COLLECTION_ID = os.getenv("HIPPOCAMPUS_COLLECTION_ID")
    FIRECRAWL_API_KEY = os.getenv("FIRECRAWL_API_KEY")
